### ISSUE TITLE
HTML Templates not working on send

### ISSUE THREAD

**Issue by daneb** [kamilc/mailman#11]
Hello ;)

I realise there is a PR for this, but I don't want others who may be considering mailman to spend time configuring and implementing a solution only to realise the problem.

I make reference to:
https://github.com/kamilc/mailman/pull/10

Thanks and look forward to the fix!
Dane

**Comment by kamilc** [comment]
This has been merged. I'll bump the version and will upload the new one to Hex very soon.

**Comment by daneb** [comment]
YAY! Thank you ;)
