### ISSUE TITLE
Cannot deal with UTF8 sender names

### ISSUE THREAD

**Issue by houshuang** [kamilc/mailman#15]
```elixir
    ** (FunctionClauseError) no function clause matching in Mailman.Render.normalize_addresses/1
        lib/mailman/render.ex:110: Mailman.Render.normalize_addresses("Stian Håklev <shaklev@gmail.com>")
```

**Comment by kamilc** [comment]
Thanks for reporting - I should have some time soon to get it fixed.

**Comment by dejanstrbac** [comment]
This is not a bug, but wrong parameter, normalize_addresses expects a list, not a string:

iex(2)> Mailman.Render.normalize_addresses(["Stian Håklev <shaklev@gmail.com>"])
["Stian Håklev <shaklev@gmail.com>"]

Cheers
