### ISSUE TITLE
Attachment without MIME type in file path

### ISSUE THREAD

**Issue by swerter** [kamilc/mailman#17]
Hi

If the attachment does not contain any MIME type information in the path, function mime_full_for_path(path) will return nil, which then brakes mime_type_for_path(path) on line 698 in file lib/mailman/attachment.ex

Would be great if you could have a look. Thanks.

**Comment by dejanstrbac** [comment]
Should be fixed with #18 , @kamilc please check, it's a very tiny PR.

**Comment by kamilc** [comment]
The #18 has been merged. Could you confirm on your end @swerter that it works well now for you? Thanks

**Comment by swerter** [comment]
Yep, all good. Thanks :)

**Comment by kamilc** [comment]
Great - Thanks
