### ISSUE TITLE
Move the config part to standard Mix.Config

### ISSUE THREAD

**Issue by kamilc** [kamilc/mailman#22]
I think it would benefit everyone to conform to the standard Mix.Config so that the learning curve would ease for newcomers.

**Comment by zmoshansky** [comment]
This would be great! I'm currently working on a meta-notification system that uses Mailman as an email adapter and this would help.

**Comment by lpil** [comment]
:+1:

**Comment by mremond** [comment]
Yes, I think this would be cool as well. As any work already been done in that direction ?

**Comment by kamilc** [comment]
Good to know you all agree it would be a good improvement. I'm booked with lots of clients work and will be for at least next couple of weeks. Is there any chance any one of you could take a stab at it?

**Comment by mremond** [comment]
Yes, that was my purpose: Make sure that it would not be duplicate work. I am using your lib for a side project, so no promise, but if I can spend enough time, I will give it a try. Thanks !

**Comment by kamilc** [comment]
Thank you so much then! :)

**Comment by kamilc** [comment]
Closed as the pull request adding that has been merged in
