### ISSUE TITLE
Ecto 2 Allowances for TestingAdapter

### ISSUE THREAD

**Issue by nathany** [kamilc/mailman#39]
When upgraded a Phoenix project to Ecto 2.0-beta.2 we see the following error in our mailer tests:

> ** (RuntimeError) cannot find ownership process

There are two solutions to this issue, as documented in [Ecto.Adapters.SQL.Sandbox](https://hexdocs.pm/ecto/2.0.0-beta.2/Ecto.Adapters.SQL.Sandbox.html).

For now we're using Shared mode, which works but runs the mailer tests synchronously. To have all the tests run concurrently, we could use Allowances in [TestingAdapter](https://github.com/kamilc/mailman/blob/master/lib/mailman/testing_adapter.ex):

```elixir
defmodule Mailman.TestingAdapter do
  @moduledoc "Implementation of the testing SMTP adapter"

  def deliver(config, _email, message) do
    parent = self() # PID of the parent process
    Task.async fn ->
      Ecto.Adapters.SQL.Sandbox.allow(TestRepo, parent, self()) # need MyApp.Repo
      if config.store_deliveries do
        Mailman.TestServer.register_delivery message
      end
      { :ok, message }
    end
  end

end
```

We've tested this out, but with the name of our Repo hard coded. Do you think it would be possible to get this working?

**Comment by keichan34** [comment]
Similar situation -- I'm working on making more of my tests async and Ecto 2.0. I'm currently using solutions in my PRs #44 and #45:

* #44 for a `MyApp.TestingAdapter` that has similar contents to what you have there, with the Repo hardcoded in. My rationale for not patching Mailman for this was because Mailman should not be dependent on Ecto.
* #45 for the actual async tests not interfering with each other

**Comment by nathany** [comment]
Thanks. 

I agree it makes sense to not depend on Ecto. Does using independent test processes have any significant impact on how quickly tests run?

**Comment by keichan34** [comment]
In my case, it's speeding tests up because the central TestServer was the bottleneck when doing a bunch of mailer tests in parallel.

**Comment by nathany** [comment]
Very nice. Thanks a bunch.

I'm gonna close this issue since you're obviously on top of it.
