### ISSUE TITLE
Change ex_doc dependency to be only for dev environment

### ISSUE THREAD

**Issue by gshaw** [kamilc/mailman#40]
I'd like to keep the `ex_doc` dependency of my project only the development environment so it isn't brought into production. I'm pretty sure the same could be said for mailman.

The fix is to add an `only` clause to the dependency.

```elixir
{ :ex_doc, ">= 0.6.0", only: :dev },
```

**Comment by Awea** [comment]
Can this be merged ?

**Comment by gshaw** [comment]
I haven't checked recently but at the time I created the PR it was good to merge.  Just waiting for the project owner to push it.

**Comment by Awea** [comment]
@gshaw Yep :) Just trying to reup.
