### ISSUE TITLE
CC/BCC emails aren't sent

### ISSUE THREAD

**Issue by skosch** [kamilc/mailman#61]
This may be related to vagabond/gen_smtp#11 – CC'ed emails show up in the header but aren't being sent, and BCC'ed addresses are ignored entirely.

Am I doing it wrong? Is this an issue with the mailserver I'm using? Please enlighten me!

(Other than that, 100 × thank you for this amazing library!)

**Comment by skosch** [comment]
.... or maybe I'm misunderstanding what CC and BCC are supposed to do, and they're really just headers –  but in that case, you need an extra field for specifying the "To" header, since `to` is already used to list all recipients.

**Comment by skosch** [comment]
Never mind me, I now see how it works. For others: if you want CC/BCC emails to be delivered, call `Mailman.deliver(email, config, :send_cc_and_bcc)`. I feel like this should be documented somewhere?

**Comment by mworrell** [comment]
The `send_cc_and_bcc` option seems to be implemented by Mailman.

gen_smtp_client is all about sending an email to a certain recipient (envelop). It doesn't look at the headers in the email to determine the recipient.

gen_smtp_client _can_ send to multiple recipients at once, _if and only if_ they are all accepted by the same relaying server (eg. a defined relay or all on the same domain).
