### ISSUE TITLE
eiconv lib being deprecated

### ISSUE THREAD

**Issue by vasspilka** [kamilc/mailman#62]
According to [eiconv](https://github.com/processone/eiconv/), it is being deprecated in favor of their new tool [iconv](https://github.com/processone/iconv/). 
Can I make a PR swapping the 2 libs?

**Comment by kamilc** [comment]
@vasspilka Thank you for the heads up - yes, you are very welcomed to create PRs :)

**Comment by vasspilka** [comment]
Ok, on it

**Comment by vasspilka** [comment]
Sry holiday mood was too distracting gonna do the PR later today

**Comment by vasspilka** [comment]
Seems this won't work out that easily, `gen_smtp` is using [zotonic/eiconv](github.com/zotonic/eiconv), same as here, however it seems that eiconv was originally created by Process One [processone/eiconv](github.com/processone/eiconv) and they are the ones to have depricated their eiconv for [processone/iconv](github.com/processone/eiconv). So we would have to start with `gen_smtp`, I'll open an issue, maybe this is a good change and will allow for further work.
