### ISSUE TITLE
Is eiconv still actually a dependency?

### ISSUE THREAD

**Issue by benwilson512** [kamilc/mailman#67]
I can't seem to find any uses in your code base. GenSMTP doesn't seem to need it either unless I missed something.

**Comment by benwilson512** [comment]
Ah yeah https://github.com/Vagabond/gen_smtp/blob/master/src/mimemail.erl uses it. Unfortunately the version listed is incompatible with the `iconv` version on hex, yay.

**Comment by kamilc** [comment]
Yup, I'll close this one then
