### ISSUE TITLE
module EEx is not available

### ISSUE THREAD

**Issue by daneb** [kamilc/mailman#7]
Hi 

I'm using mailman on Mac OS X Yosemite (10.10.2).
I followed the tutorial as specified but ran into the following error when sending an email.

My configuration:

```elixir
def config do
    %Mailman.Context{
      config:   %Mailman.SmtpConfig{ relay: "mailserver.xxxx.co.za", port: 25 },
      composer: %Mailman.EexComposeConfig{}
    }
  end
```

```
** (UndefinedFunctionError) undefined function: EEx.eval_string/2 (module EEx is not available)
    EEx.eval_string("", [name: "Yo"])
    lib/mailman/render.ex:127: Mailman.Render.compile_parts/2
    lib/mailman/render.ex:6: Mailman.Render.render/2
    lib/mailman.ex:15: Mailman.deliver/2
    (elixir) lib/kernel/cli.ex:70: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

Am I missing something obvious?
Please let me know if I can assist or provide more information....

**Comment by kamilc** [comment]
I'll troubleshoot - it seems strange at first glance. Thanks for filing a bug!

**Comment by kamilc** [comment]
@daneb It seems very strange - the EEx module comes with Elixir. Which version of Elixir are you running?

**Comment by daneb** [comment]
Exactly!
I've put the repo online, maybe I've done something wrong.

https://github.com/daneb/ice

Elixir 1.0.4
Erlang/OTP 17

**Comment by kamilc** [comment]
It works just fine on my machine... Later I'll try upgrading Elixir from 1.0.0 to 1.0.4 and try again

**Comment by daneb** [comment]
Excellent - thanks for the feedback

**Comment by daneb** [comment]
A friend ran this on Mac OS X 10.10.2 with 1.0.2 and ran into the same issue.
What OS are you running?

**Comment by daneb** [comment]
Ok fixed! 
[applications: [:logger, :eex]]
