### ISSUE TITLE
Any example of using a Third Party SMTP server?

### ISSUE THREAD

**Issue by bradcypert** [kamilc/mailman#9]
I'm interested in using Google's SMTP server as I'm not able to run one locally. Can an example be provided for hooking into a third-party SMTP ? I tried exploring the codebase, but I'm relatively new to Elixir, too.

Thanks!

**Comment by daneb** [comment]
I've just implemented something basic while I was on the same path as you.
[Github](https://github.com/daneb/ice/tree/master/lib)

**Comment by kamilc** [comment]
@bradcypert Did the above advice work for you? If so would you please go ahead and close the ticket? Thanks

**Comment by bradcypert** [comment]
Sorry! That definitely did work for me! Closing.

**Comment by houshuang** [comment]
It would be useful to add a simple example of the SmtpConfig struct in the README, I always have to look up in the code to find the fields.
